# Basic Dependabot configuration for npm and GitHub Actions
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "radice21011-eng"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
