name: Setup Repository Secrets
on:
  workflow_dispatch:
    inputs:
      secrets:
        description: 'JSON object of secrets to add. e.g., {"API_KEY": "value1", "DB_PASS": "value2"}'
        required: true
        type: string

jobs:
  add-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Add repository secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRETS_JSON: ${{ inputs.secrets }}
        run: |
          echo "$SECRETS_JSON" | jq -r 'to_entries|map("gh secret set \(.key) -b \"\(.value)\"")|.[]' | while read -r cmd; do
            eval $cmd
          done
